/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopologyRouteImport } from './routes/topology'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ControlplaneRouteImport } from './routes/controlplane'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantsIndexRouteImport } from './routes/tenants.index'
import { Route as NodesIndexRouteImport } from './routes/nodes.index'
import { Route as InstancesIndexRouteImport } from './routes/instances.index'
import { Route as DeploymentsIndexRouteImport } from './routes/deployments.index'
import { Route as TenantsIdRouteImport } from './routes/tenants.$id'
import { Route as NodesNodeIdRouteImport } from './routes/nodes.$nodeId'
import { Route as DeploymentsNewRouteImport } from './routes/deployments.new'
import { Route as DeploymentsNameRouteImport } from './routes/deployments.$name'
import { Route as InstancesNameIdxRouteImport } from './routes/instances.$name.$idx'

const TopologyRoute = TopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlplaneRoute = ControlplaneRouteImport.update({
  id: '/controlplane',
  path: '/controlplane',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIndexRoute = NodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesIndexRoute = InstancesIndexRouteImport.update({
  id: '/instances/',
  path: '/instances/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIndexRoute = DeploymentsIndexRouteImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIdRoute = TenantsIdRouteImport.update({
  id: '/tenants/$id',
  path: '/tenants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesNodeIdRoute = NodesNodeIdRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsNewRoute = DeploymentsNewRouteImport.update({
  id: '/deployments/new',
  path: '/deployments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsNameRoute = DeploymentsNameRouteImport.update({
  id: '/deployments/$name',
  path: '/deployments/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesNameIdxRoute = InstancesNameIdxRouteImport.update({
  id: '/instances/$name/$idx',
  path: '/instances/$name/$idx',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/controlplane': typeof ControlplaneRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/topology': typeof TopologyRoute
  '/deployments/$name': typeof DeploymentsNameRoute
  '/deployments/new': typeof DeploymentsNewRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/tenants/$id': typeof TenantsIdRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/instances/': typeof InstancesIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/instances/$name/$idx': typeof InstancesNameIdxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/controlplane': typeof ControlplaneRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/topology': typeof TopologyRoute
  '/deployments/$name': typeof DeploymentsNameRoute
  '/deployments/new': typeof DeploymentsNewRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/tenants/$id': typeof TenantsIdRoute
  '/deployments': typeof DeploymentsIndexRoute
  '/instances': typeof InstancesIndexRoute
  '/nodes': typeof NodesIndexRoute
  '/tenants': typeof TenantsIndexRoute
  '/instances/$name/$idx': typeof InstancesNameIdxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/controlplane': typeof ControlplaneRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/topology': typeof TopologyRoute
  '/deployments/$name': typeof DeploymentsNameRoute
  '/deployments/new': typeof DeploymentsNewRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/tenants/$id': typeof TenantsIdRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/instances/': typeof InstancesIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/instances/$name/$idx': typeof InstancesNameIdxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/controlplane'
    | '/logs'
    | '/metrics'
    | '/topology'
    | '/deployments/$name'
    | '/deployments/new'
    | '/nodes/$nodeId'
    | '/tenants/$id'
    | '/deployments/'
    | '/instances/'
    | '/nodes/'
    | '/tenants/'
    | '/instances/$name/$idx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config'
    | '/controlplane'
    | '/logs'
    | '/metrics'
    | '/topology'
    | '/deployments/$name'
    | '/deployments/new'
    | '/nodes/$nodeId'
    | '/tenants/$id'
    | '/deployments'
    | '/instances'
    | '/nodes'
    | '/tenants'
    | '/instances/$name/$idx'
  id:
    | '__root__'
    | '/'
    | '/config'
    | '/controlplane'
    | '/logs'
    | '/metrics'
    | '/topology'
    | '/deployments/$name'
    | '/deployments/new'
    | '/nodes/$nodeId'
    | '/tenants/$id'
    | '/deployments/'
    | '/instances/'
    | '/nodes/'
    | '/tenants/'
    | '/instances/$name/$idx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRoute: typeof ConfigRoute
  ControlplaneRoute: typeof ControlplaneRoute
  LogsRoute: typeof LogsRoute
  MetricsRoute: typeof MetricsRoute
  TopologyRoute: typeof TopologyRoute
  DeploymentsNameRoute: typeof DeploymentsNameRoute
  DeploymentsNewRoute: typeof DeploymentsNewRoute
  NodesNodeIdRoute: typeof NodesNodeIdRoute
  TenantsIdRoute: typeof TenantsIdRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
  InstancesIndexRoute: typeof InstancesIndexRoute
  NodesIndexRoute: typeof NodesIndexRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
  InstancesNameIdxRoute: typeof InstancesNameIdxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topology': {
      id: '/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof TopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controlplane': {
      id: '/controlplane'
      path: '/controlplane'
      fullPath: '/controlplane'
      preLoaderRoute: typeof ControlplaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/': {
      id: '/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof NodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances/': {
      id: '/instances/'
      path: '/instances'
      fullPath: '/instances/'
      preLoaderRoute: typeof InstancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/': {
      id: '/deployments/'
      path: '/deployments'
      fullPath: '/deployments/'
      preLoaderRoute: typeof DeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/$id': {
      id: '/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/tenants/$id'
      preLoaderRoute: typeof TenantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/$nodeId': {
      id: '/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/nodes/$nodeId'
      preLoaderRoute: typeof NodesNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/new': {
      id: '/deployments/new'
      path: '/deployments/new'
      fullPath: '/deployments/new'
      preLoaderRoute: typeof DeploymentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/$name': {
      id: '/deployments/$name'
      path: '/deployments/$name'
      fullPath: '/deployments/$name'
      preLoaderRoute: typeof DeploymentsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances/$name/$idx': {
      id: '/instances/$name/$idx'
      path: '/instances/$name/$idx'
      fullPath: '/instances/$name/$idx'
      preLoaderRoute: typeof InstancesNameIdxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRoute: ConfigRoute,
  ControlplaneRoute: ControlplaneRoute,
  LogsRoute: LogsRoute,
  MetricsRoute: MetricsRoute,
  TopologyRoute: TopologyRoute,
  DeploymentsNameRoute: DeploymentsNameRoute,
  DeploymentsNewRoute: DeploymentsNewRoute,
  NodesNodeIdRoute: NodesNodeIdRoute,
  TenantsIdRoute: TenantsIdRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
  InstancesIndexRoute: InstancesIndexRoute,
  NodesIndexRoute: NodesIndexRoute,
  TenantsIndexRoute: TenantsIndexRoute,
  InstancesNameIdxRoute: InstancesNameIdxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
