/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolumesRouteImport } from './routes/volumes'
import { Route as TracesRouteImport } from './routes/traces'
import { Route as TopologyRouteImport } from './routes/topology'
import { Route as SkaldRouteImport } from './routes/skald'
import { Route as SecretsRouteImport } from './routes/secrets'
import { Route as SecretmapsRouteImport } from './routes/secretmaps'
import { Route as SealRouteImport } from './routes/seal'
import { Route as NetworkingRouteImport } from './routes/networking'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LimitrangesRouteImport } from './routes/limitranges'
import { Route as GatewayRouteImport } from './routes/gateway'
import { Route as CustomResourcesRouteImport } from './routes/custom-resources'
import { Route as ControlplaneRouteImport } from './routes/controlplane'
import { Route as ConfigmapsRouteImport } from './routes/configmaps'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as AccessControlRouteImport } from './routes/access-control'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantsIndexRouteImport } from './routes/tenants.index'
import { Route as StatefulsetsIndexRouteImport } from './routes/statefulsets.index'
import { Route as NodesIndexRouteImport } from './routes/nodes.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as InstancesIndexRouteImport } from './routes/instances.index'
import { Route as DeploymentsIndexRouteImport } from './routes/deployments.index'
import { Route as DaemonsetsIndexRouteImport } from './routes/daemonsets.index'
import { Route as CronjobsIndexRouteImport } from './routes/cronjobs.index'
import { Route as AppsIndexRouteImport } from './routes/apps.index'
import { Route as TenantsIdRouteImport } from './routes/tenants.$id'
import { Route as StatefulsetsNameRouteImport } from './routes/statefulsets.$name'
import { Route as NodesNodeIdRouteImport } from './routes/nodes.$nodeId'
import { Route as JobsNewRouteImport } from './routes/jobs.new'
import { Route as JobsNameRouteImport } from './routes/jobs.$name'
import { Route as DeploymentsNewRouteImport } from './routes/deployments.new'
import { Route as DeploymentsNameRouteImport } from './routes/deployments.$name'
import { Route as DaemonsetsNameRouteImport } from './routes/daemonsets.$name'
import { Route as CronjobsNewRouteImport } from './routes/cronjobs.new'
import { Route as CronjobsNameRouteImport } from './routes/cronjobs.$name'
import { Route as InstancesNameIdxRouteImport } from './routes/instances.$name.$idx'
import { Route as AppsKindNameRouteImport } from './routes/apps.$kind.$name'

const VolumesRoute = VolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesRoute = TracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const TopologyRoute = TopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => rootRouteImport,
} as any)
const SkaldRoute = SkaldRouteImport.update({
  id: '/skald',
  path: '/skald',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretmapsRoute = SecretmapsRouteImport.update({
  id: '/secretmaps',
  path: '/secretmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const SealRoute = SealRouteImport.update({
  id: '/seal',
  path: '/seal',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkingRoute = NetworkingRouteImport.update({
  id: '/networking',
  path: '/networking',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitrangesRoute = LimitrangesRouteImport.update({
  id: '/limitranges',
  path: '/limitranges',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewayRoute = GatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomResourcesRoute = CustomResourcesRouteImport.update({
  id: '/custom-resources',
  path: '/custom-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlplaneRoute = ControlplaneRouteImport.update({
  id: '/controlplane',
  path: '/controlplane',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigmapsRoute = ConfigmapsRouteImport.update({
  id: '/configmaps',
  path: '/configmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessControlRoute = AccessControlRouteImport.update({
  id: '/access-control',
  path: '/access-control',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatefulsetsIndexRoute = StatefulsetsIndexRouteImport.update({
  id: '/statefulsets/',
  path: '/statefulsets/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIndexRoute = NodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesIndexRoute = InstancesIndexRouteImport.update({
  id: '/instances/',
  path: '/instances/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIndexRoute = DeploymentsIndexRouteImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DaemonsetsIndexRoute = DaemonsetsIndexRouteImport.update({
  id: '/daemonsets/',
  path: '/daemonsets/',
  getParentRoute: () => rootRouteImport,
} as any)
const CronjobsIndexRoute = CronjobsIndexRouteImport.update({
  id: '/cronjobs/',
  path: '/cronjobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIdRoute = TenantsIdRouteImport.update({
  id: '/tenants/$id',
  path: '/tenants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StatefulsetsNameRoute = StatefulsetsNameRouteImport.update({
  id: '/statefulsets/$name',
  path: '/statefulsets/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesNodeIdRoute = NodesNodeIdRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNameRoute = JobsNameRouteImport.update({
  id: '/jobs/$name',
  path: '/jobs/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsNewRoute = DeploymentsNewRouteImport.update({
  id: '/deployments/new',
  path: '/deployments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsNameRoute = DeploymentsNameRouteImport.update({
  id: '/deployments/$name',
  path: '/deployments/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const DaemonsetsNameRoute = DaemonsetsNameRouteImport.update({
  id: '/daemonsets/$name',
  path: '/daemonsets/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CronjobsNewRoute = CronjobsNewRouteImport.update({
  id: '/cronjobs/new',
  path: '/cronjobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CronjobsNameRoute = CronjobsNameRouteImport.update({
  id: '/cronjobs/$name',
  path: '/cronjobs/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesNameIdxRoute = InstancesNameIdxRouteImport.update({
  id: '/instances/$name/$idx',
  path: '/instances/$name/$idx',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsKindNameRoute = AppsKindNameRouteImport.update({
  id: '/apps/$kind/$name',
  path: '/apps/$kind/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-control': typeof AccessControlRoute
  '/artifacts': typeof ArtifactsRoute
  '/audit': typeof AuditRoute
  '/config': typeof ConfigRoute
  '/configmaps': typeof ConfigmapsRoute
  '/controlplane': typeof ControlplaneRoute
  '/custom-resources': typeof CustomResourcesRoute
  '/gateway': typeof GatewayRoute
  '/limitranges': typeof LimitrangesRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/networking': typeof NetworkingRoute
  '/seal': typeof SealRoute
  '/secretmaps': typeof SecretmapsRoute
  '/secrets': typeof SecretsRoute
  '/skald': typeof SkaldRoute
  '/topology': typeof TopologyRoute
  '/traces': typeof TracesRoute
  '/volumes': typeof VolumesRoute
  '/cronjobs/$name': typeof CronjobsNameRoute
  '/cronjobs/new': typeof CronjobsNewRoute
  '/daemonsets/$name': typeof DaemonsetsNameRoute
  '/deployments/$name': typeof DeploymentsNameRoute
  '/deployments/new': typeof DeploymentsNewRoute
  '/jobs/$name': typeof JobsNameRoute
  '/jobs/new': typeof JobsNewRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/statefulsets/$name': typeof StatefulsetsNameRoute
  '/tenants/$id': typeof TenantsIdRoute
  '/apps/': typeof AppsIndexRoute
  '/cronjobs/': typeof CronjobsIndexRoute
  '/daemonsets/': typeof DaemonsetsIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/instances/': typeof InstancesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/statefulsets/': typeof StatefulsetsIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/apps/$kind/$name': typeof AppsKindNameRoute
  '/instances/$name/$idx': typeof InstancesNameIdxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-control': typeof AccessControlRoute
  '/artifacts': typeof ArtifactsRoute
  '/audit': typeof AuditRoute
  '/config': typeof ConfigRoute
  '/configmaps': typeof ConfigmapsRoute
  '/controlplane': typeof ControlplaneRoute
  '/custom-resources': typeof CustomResourcesRoute
  '/gateway': typeof GatewayRoute
  '/limitranges': typeof LimitrangesRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/networking': typeof NetworkingRoute
  '/seal': typeof SealRoute
  '/secretmaps': typeof SecretmapsRoute
  '/secrets': typeof SecretsRoute
  '/skald': typeof SkaldRoute
  '/topology': typeof TopologyRoute
  '/traces': typeof TracesRoute
  '/volumes': typeof VolumesRoute
  '/cronjobs/$name': typeof CronjobsNameRoute
  '/cronjobs/new': typeof CronjobsNewRoute
  '/daemonsets/$name': typeof DaemonsetsNameRoute
  '/deployments/$name': typeof DeploymentsNameRoute
  '/deployments/new': typeof DeploymentsNewRoute
  '/jobs/$name': typeof JobsNameRoute
  '/jobs/new': typeof JobsNewRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/statefulsets/$name': typeof StatefulsetsNameRoute
  '/tenants/$id': typeof TenantsIdRoute
  '/apps': typeof AppsIndexRoute
  '/cronjobs': typeof CronjobsIndexRoute
  '/daemonsets': typeof DaemonsetsIndexRoute
  '/deployments': typeof DeploymentsIndexRoute
  '/instances': typeof InstancesIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/nodes': typeof NodesIndexRoute
  '/statefulsets': typeof StatefulsetsIndexRoute
  '/tenants': typeof TenantsIndexRoute
  '/apps/$kind/$name': typeof AppsKindNameRoute
  '/instances/$name/$idx': typeof InstancesNameIdxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-control': typeof AccessControlRoute
  '/artifacts': typeof ArtifactsRoute
  '/audit': typeof AuditRoute
  '/config': typeof ConfigRoute
  '/configmaps': typeof ConfigmapsRoute
  '/controlplane': typeof ControlplaneRoute
  '/custom-resources': typeof CustomResourcesRoute
  '/gateway': typeof GatewayRoute
  '/limitranges': typeof LimitrangesRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/networking': typeof NetworkingRoute
  '/seal': typeof SealRoute
  '/secretmaps': typeof SecretmapsRoute
  '/secrets': typeof SecretsRoute
  '/skald': typeof SkaldRoute
  '/topology': typeof TopologyRoute
  '/traces': typeof TracesRoute
  '/volumes': typeof VolumesRoute
  '/cronjobs/$name': typeof CronjobsNameRoute
  '/cronjobs/new': typeof CronjobsNewRoute
  '/daemonsets/$name': typeof DaemonsetsNameRoute
  '/deployments/$name': typeof DeploymentsNameRoute
  '/deployments/new': typeof DeploymentsNewRoute
  '/jobs/$name': typeof JobsNameRoute
  '/jobs/new': typeof JobsNewRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/statefulsets/$name': typeof StatefulsetsNameRoute
  '/tenants/$id': typeof TenantsIdRoute
  '/apps/': typeof AppsIndexRoute
  '/cronjobs/': typeof CronjobsIndexRoute
  '/daemonsets/': typeof DaemonsetsIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/instances/': typeof InstancesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/statefulsets/': typeof StatefulsetsIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/apps/$kind/$name': typeof AppsKindNameRoute
  '/instances/$name/$idx': typeof InstancesNameIdxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-control'
    | '/artifacts'
    | '/audit'
    | '/config'
    | '/configmaps'
    | '/controlplane'
    | '/custom-resources'
    | '/gateway'
    | '/limitranges'
    | '/login'
    | '/logs'
    | '/metrics'
    | '/networking'
    | '/seal'
    | '/secretmaps'
    | '/secrets'
    | '/skald'
    | '/topology'
    | '/traces'
    | '/volumes'
    | '/cronjobs/$name'
    | '/cronjobs/new'
    | '/daemonsets/$name'
    | '/deployments/$name'
    | '/deployments/new'
    | '/jobs/$name'
    | '/jobs/new'
    | '/nodes/$nodeId'
    | '/statefulsets/$name'
    | '/tenants/$id'
    | '/apps/'
    | '/cronjobs/'
    | '/daemonsets/'
    | '/deployments/'
    | '/instances/'
    | '/jobs/'
    | '/nodes/'
    | '/statefulsets/'
    | '/tenants/'
    | '/apps/$kind/$name'
    | '/instances/$name/$idx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-control'
    | '/artifacts'
    | '/audit'
    | '/config'
    | '/configmaps'
    | '/controlplane'
    | '/custom-resources'
    | '/gateway'
    | '/limitranges'
    | '/login'
    | '/logs'
    | '/metrics'
    | '/networking'
    | '/seal'
    | '/secretmaps'
    | '/secrets'
    | '/skald'
    | '/topology'
    | '/traces'
    | '/volumes'
    | '/cronjobs/$name'
    | '/cronjobs/new'
    | '/daemonsets/$name'
    | '/deployments/$name'
    | '/deployments/new'
    | '/jobs/$name'
    | '/jobs/new'
    | '/nodes/$nodeId'
    | '/statefulsets/$name'
    | '/tenants/$id'
    | '/apps'
    | '/cronjobs'
    | '/daemonsets'
    | '/deployments'
    | '/instances'
    | '/jobs'
    | '/nodes'
    | '/statefulsets'
    | '/tenants'
    | '/apps/$kind/$name'
    | '/instances/$name/$idx'
  id:
    | '__root__'
    | '/'
    | '/access-control'
    | '/artifacts'
    | '/audit'
    | '/config'
    | '/configmaps'
    | '/controlplane'
    | '/custom-resources'
    | '/gateway'
    | '/limitranges'
    | '/login'
    | '/logs'
    | '/metrics'
    | '/networking'
    | '/seal'
    | '/secretmaps'
    | '/secrets'
    | '/skald'
    | '/topology'
    | '/traces'
    | '/volumes'
    | '/cronjobs/$name'
    | '/cronjobs/new'
    | '/daemonsets/$name'
    | '/deployments/$name'
    | '/deployments/new'
    | '/jobs/$name'
    | '/jobs/new'
    | '/nodes/$nodeId'
    | '/statefulsets/$name'
    | '/tenants/$id'
    | '/apps/'
    | '/cronjobs/'
    | '/daemonsets/'
    | '/deployments/'
    | '/instances/'
    | '/jobs/'
    | '/nodes/'
    | '/statefulsets/'
    | '/tenants/'
    | '/apps/$kind/$name'
    | '/instances/$name/$idx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessControlRoute: typeof AccessControlRoute
  ArtifactsRoute: typeof ArtifactsRoute
  AuditRoute: typeof AuditRoute
  ConfigRoute: typeof ConfigRoute
  ConfigmapsRoute: typeof ConfigmapsRoute
  ControlplaneRoute: typeof ControlplaneRoute
  CustomResourcesRoute: typeof CustomResourcesRoute
  GatewayRoute: typeof GatewayRoute
  LimitrangesRoute: typeof LimitrangesRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  MetricsRoute: typeof MetricsRoute
  NetworkingRoute: typeof NetworkingRoute
  SealRoute: typeof SealRoute
  SecretmapsRoute: typeof SecretmapsRoute
  SecretsRoute: typeof SecretsRoute
  SkaldRoute: typeof SkaldRoute
  TopologyRoute: typeof TopologyRoute
  TracesRoute: typeof TracesRoute
  VolumesRoute: typeof VolumesRoute
  CronjobsNameRoute: typeof CronjobsNameRoute
  CronjobsNewRoute: typeof CronjobsNewRoute
  DaemonsetsNameRoute: typeof DaemonsetsNameRoute
  DeploymentsNameRoute: typeof DeploymentsNameRoute
  DeploymentsNewRoute: typeof DeploymentsNewRoute
  JobsNameRoute: typeof JobsNameRoute
  JobsNewRoute: typeof JobsNewRoute
  NodesNodeIdRoute: typeof NodesNodeIdRoute
  StatefulsetsNameRoute: typeof StatefulsetsNameRoute
  TenantsIdRoute: typeof TenantsIdRoute
  AppsIndexRoute: typeof AppsIndexRoute
  CronjobsIndexRoute: typeof CronjobsIndexRoute
  DaemonsetsIndexRoute: typeof DaemonsetsIndexRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
  InstancesIndexRoute: typeof InstancesIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  NodesIndexRoute: typeof NodesIndexRoute
  StatefulsetsIndexRoute: typeof StatefulsetsIndexRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
  AppsKindNameRoute: typeof AppsKindNameRoute
  InstancesNameIdxRoute: typeof InstancesNameIdxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volumes': {
      id: '/volumes'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof VolumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces': {
      id: '/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topology': {
      id: '/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof TopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skald': {
      id: '/skald'
      path: '/skald'
      fullPath: '/skald'
      preLoaderRoute: typeof SkaldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretmaps': {
      id: '/secretmaps'
      path: '/secretmaps'
      fullPath: '/secretmaps'
      preLoaderRoute: typeof SecretmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seal': {
      id: '/seal'
      path: '/seal'
      fullPath: '/seal'
      preLoaderRoute: typeof SealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networking': {
      id: '/networking'
      path: '/networking'
      fullPath: '/networking'
      preLoaderRoute: typeof NetworkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limitranges': {
      id: '/limitranges'
      path: '/limitranges'
      fullPath: '/limitranges'
      preLoaderRoute: typeof LimitrangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateway': {
      id: '/gateway'
      path: '/gateway'
      fullPath: '/gateway'
      preLoaderRoute: typeof GatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-resources': {
      id: '/custom-resources'
      path: '/custom-resources'
      fullPath: '/custom-resources'
      preLoaderRoute: typeof CustomResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controlplane': {
      id: '/controlplane'
      path: '/controlplane'
      fullPath: '/controlplane'
      preLoaderRoute: typeof ControlplaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configmaps': {
      id: '/configmaps'
      path: '/configmaps'
      fullPath: '/configmaps'
      preLoaderRoute: typeof ConfigmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-control': {
      id: '/access-control'
      path: '/access-control'
      fullPath: '/access-control'
      preLoaderRoute: typeof AccessControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statefulsets/': {
      id: '/statefulsets/'
      path: '/statefulsets'
      fullPath: '/statefulsets/'
      preLoaderRoute: typeof StatefulsetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/': {
      id: '/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof NodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances/': {
      id: '/instances/'
      path: '/instances'
      fullPath: '/instances/'
      preLoaderRoute: typeof InstancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/': {
      id: '/deployments/'
      path: '/deployments'
      fullPath: '/deployments/'
      preLoaderRoute: typeof DeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daemonsets/': {
      id: '/daemonsets/'
      path: '/daemonsets'
      fullPath: '/daemonsets/'
      preLoaderRoute: typeof DaemonsetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronjobs/': {
      id: '/cronjobs/'
      path: '/cronjobs'
      fullPath: '/cronjobs/'
      preLoaderRoute: typeof CronjobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/$id': {
      id: '/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/tenants/$id'
      preLoaderRoute: typeof TenantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statefulsets/$name': {
      id: '/statefulsets/$name'
      path: '/statefulsets/$name'
      fullPath: '/statefulsets/$name'
      preLoaderRoute: typeof StatefulsetsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/$nodeId': {
      id: '/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/nodes/$nodeId'
      preLoaderRoute: typeof NodesNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$name': {
      id: '/jobs/$name'
      path: '/jobs/$name'
      fullPath: '/jobs/$name'
      preLoaderRoute: typeof JobsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/new': {
      id: '/deployments/new'
      path: '/deployments/new'
      fullPath: '/deployments/new'
      preLoaderRoute: typeof DeploymentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/$name': {
      id: '/deployments/$name'
      path: '/deployments/$name'
      fullPath: '/deployments/$name'
      preLoaderRoute: typeof DeploymentsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daemonsets/$name': {
      id: '/daemonsets/$name'
      path: '/daemonsets/$name'
      fullPath: '/daemonsets/$name'
      preLoaderRoute: typeof DaemonsetsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronjobs/new': {
      id: '/cronjobs/new'
      path: '/cronjobs/new'
      fullPath: '/cronjobs/new'
      preLoaderRoute: typeof CronjobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronjobs/$name': {
      id: '/cronjobs/$name'
      path: '/cronjobs/$name'
      fullPath: '/cronjobs/$name'
      preLoaderRoute: typeof CronjobsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances/$name/$idx': {
      id: '/instances/$name/$idx'
      path: '/instances/$name/$idx'
      fullPath: '/instances/$name/$idx'
      preLoaderRoute: typeof InstancesNameIdxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$kind/$name': {
      id: '/apps/$kind/$name'
      path: '/apps/$kind/$name'
      fullPath: '/apps/$kind/$name'
      preLoaderRoute: typeof AppsKindNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessControlRoute: AccessControlRoute,
  ArtifactsRoute: ArtifactsRoute,
  AuditRoute: AuditRoute,
  ConfigRoute: ConfigRoute,
  ConfigmapsRoute: ConfigmapsRoute,
  ControlplaneRoute: ControlplaneRoute,
  CustomResourcesRoute: CustomResourcesRoute,
  GatewayRoute: GatewayRoute,
  LimitrangesRoute: LimitrangesRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  MetricsRoute: MetricsRoute,
  NetworkingRoute: NetworkingRoute,
  SealRoute: SealRoute,
  SecretmapsRoute: SecretmapsRoute,
  SecretsRoute: SecretsRoute,
  SkaldRoute: SkaldRoute,
  TopologyRoute: TopologyRoute,
  TracesRoute: TracesRoute,
  VolumesRoute: VolumesRoute,
  CronjobsNameRoute: CronjobsNameRoute,
  CronjobsNewRoute: CronjobsNewRoute,
  DaemonsetsNameRoute: DaemonsetsNameRoute,
  DeploymentsNameRoute: DeploymentsNameRoute,
  DeploymentsNewRoute: DeploymentsNewRoute,
  JobsNameRoute: JobsNameRoute,
  JobsNewRoute: JobsNewRoute,
  NodesNodeIdRoute: NodesNodeIdRoute,
  StatefulsetsNameRoute: StatefulsetsNameRoute,
  TenantsIdRoute: TenantsIdRoute,
  AppsIndexRoute: AppsIndexRoute,
  CronjobsIndexRoute: CronjobsIndexRoute,
  DaemonsetsIndexRoute: DaemonsetsIndexRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
  InstancesIndexRoute: InstancesIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  NodesIndexRoute: NodesIndexRoute,
  StatefulsetsIndexRoute: StatefulsetsIndexRoute,
  TenantsIndexRoute: TenantsIndexRoute,
  AppsKindNameRoute: AppsKindNameRoute,
  InstancesNameIdxRoute: InstancesNameIdxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
