package com.gimle.hilmir.init;

/**
 * Renders {@code deployment.yaml} text (a {@code kind: Deployment} workload manifest), in either of
 * the platform's two hosting-mode shapes -- module-hosting (a plain {@code module:}/{@code
 * artifactPath} reference) or vessel-hosting (the same, plus a {@code vessel:} block, matching the
 * schema documented alongside every other workload kind). Vessel form is used only when the source
 * jar structurally cannot carry a {@code gimle-module.yaml} at all (no {@code module-info.class},
 * or a launcher-archive layout) -- this never guesses at a module descriptor for something that
 * can't have one.
 */
public final class DeploymentYamlWriter {

  private DeploymentYamlWriter() {}

  public static String renderModuleForm(String name, boolean nameConfident, String jarPath) {
    StringBuilder sb = new StringBuilder();
    sb.append("# Generated by `hilmir init` -- verify every field before deploying.\n");
    sb.append(
        "# This is a raw Deployment manifest, not a bundle: submit it directly to the control\n");
    sb.append(
        "# plane (gimle-cli, or PUT /deployments/<name>), or wrap it as workloads: [{file:\n");
    sb.append("# <this file>}] inside a kind: Bundle document for `hilmir deploy` -- `hilmir\n");
    sb.append("# deploy` does not accept a Deployment manifest like this one directly.\n");
    sb.append("kind: Deployment\n");
    sb.append("name: ").append(name).append("-deployment\n");
    sb.append("module:\n");
    sb.append("  name: ").append(name);
    if (!nameConfident) {
      sb.append(
          " # TODO: derived from the jar's file name, not module-info.class -- confirm this"
              + " matches gimle-module.yaml's own name");
    }
    sb.append('\n');
    sb.append("  version: 0.1.0 # TODO: keep in sync with gimle-module.yaml's own version\n");
    sb.append("artifactPath: ")
        .append(jarPath)
        .append(" # TODO: or leave blank to resolve from the artifact registry instead\n");
    sb.append("replicas: 1\n");
    return sb.toString();
  }

  public static String renderVesselForm(String name, String jarPath) {
    StringBuilder sb = new StringBuilder();
    sb.append(
        "# Generated by `hilmir init` -- this jar looks vessel-shaped (no module-info.class,\n");
    sb.append(
        "# or a launcher-archive layout), so no gimle-module.yaml is possible for it: this\n");
    sb.append(
        "# deployment carries all configuration itself via the vessel: block below. Verify\n");
    sb.append("# every field before deploying.\n");
    sb.append(
        "# This is a raw Deployment manifest, not a bundle: submit it directly to the control\n");
    sb.append(
        "# plane (gimle-cli, or PUT /deployments/<name>), or wrap it as workloads: [{file:\n");
    sb.append("# <this file>}] inside a kind: Bundle document for `hilmir deploy` -- `hilmir\n");
    sb.append("# deploy` does not accept a Deployment manifest like this one directly.\n");
    sb.append("kind: Deployment\n");
    sb.append("name: ").append(name).append("-deployment\n");
    sb.append("module:\n");
    sb.append("  name: ")
        .append(name)
        .append(
            " # TODO: pick a real identifier -- a vessel has no module-info to read one from\n");
    sb.append("  version: 0.1.0 # TODO: set the real version\n");
    sb.append("artifactPath: ")
        .append(jarPath)
        .append(" # TODO: or leave blank to resolve from the artifact registry instead\n");
    sb.append("replicas: 1\n");
    sb.append("vessel:\n");
    sb.append("  args: [] # TODO: extra program arguments, if any\n");
    sb.append("  jvmFlags: [] # TODO: extra JVM flags, if any\n");
    sb.append("  resources:\n");
    sb.append("    request: {memory: 128Mi, cpu: 50m} # TODO: measure and adjust\n");
    sb.append("    limit: {memory: 256Mi, cpu: 250m} # TODO: measure and adjust\n");
    return sb.toString();
  }
}
