package com.gimle.hilmir.init;

import java.util.Optional;

/**
 * Renders {@code gimle-module.yaml} text for a module-hosting artifact, matching {@code
 * ModuleDescriptorParser}'s exact schema field-for-field ({@code isolation.tier}, {@code
 * resources.request/limit.{memory,cpu}}, {@code health.{liveness,readiness}}, {@code
 * lifecycle.{hooks,jobHooks}}) so the generated file parses back through the real parser unchanged
 * -- verified by {@code ModuleYamlWriterTest}'s own round-trip check. Fields analysis can be
 * confident about (probe/hook classes actually found implementing the right interface, with a
 * no-arg constructor) are filled in directly; everything else (version, resource sizing, isolation
 * tier) gets a conservative default plus a {@code # TODO} comment, never a silent guess.
 */
public final class ModuleYamlWriter {

  private ModuleYamlWriter() {}

  public record Detected(
      String moduleName,
      boolean nameConfident,
      Optional<String> livenessClass,
      Optional<String> readinessClass,
      Optional<String> lifecycleHooksClass,
      Optional<String> jobHooksClass) {}

  public static String render(Detected detected) {
    StringBuilder sb = new StringBuilder();
    sb.append("# Generated by `hilmir init` -- verify every field, especially the TODO-marked\n");
    sb.append("# ones, before deploying. Field shapes match ModuleDescriptorParser exactly.\n");
    sb.append("name: ").append(detected.moduleName());
    if (!detected.nameConfident()) {
      sb.append(
          " # TODO: derived from the jar's file name, not module-info.class -- confirm this"
              + " is a valid dotted module identifier");
    }
    sb.append('\n');
    sb.append("version: 0.1.0 # TODO: set the real version\n");
    sb.append("isolation:\n");
    sb.append(
        "  tier: TIER_1 # TODO: use TIER_2 if this module needs its own dedicated worker JVM\n");
    sb.append("resources:\n");
    sb.append("  request:\n");
    sb.append("    memory: 32Mi # TODO: measure and adjust\n");
    sb.append("    cpu: 20m # TODO: measure and adjust\n");
    sb.append("  limit:\n");
    sb.append("    memory: 64Mi # TODO: measure and adjust\n");
    sb.append("    cpu: 100m # TODO: measure and adjust\n");
    appendHealth(sb, detected);
    appendLifecycle(sb, detected);
    return sb.toString();
  }

  private static void appendHealth(StringBuilder sb, Detected detected) {
    if (detected.livenessClass().isEmpty() && detected.readinessClass().isEmpty()) {
      sb.append(
          "# health: # TODO: no LivenessProbe/ReadinessProbe implementation was found in the"
              + " jar\n");
      sb.append("#   liveness: <fully.qualified.ClassName>\n");
      sb.append("#   readiness: <fully.qualified.ClassName>\n");
      return;
    }
    sb.append("health:\n");
    detected.livenessClass().ifPresent(c -> sb.append("  liveness: ").append(c).append('\n'));
    detected.readinessClass().ifPresent(c -> sb.append("  readiness: ").append(c).append('\n'));
  }

  private static void appendLifecycle(StringBuilder sb, Detected detected) {
    if (detected.lifecycleHooksClass().isEmpty() && detected.jobHooksClass().isEmpty()) {
      return;
    }
    sb.append("lifecycle:\n");
    detected.lifecycleHooksClass().ifPresent(c -> sb.append("  hooks: ").append(c).append('\n'));
    if (detected.jobHooksClass().isPresent()) {
      if (detected.lifecycleHooksClass().isPresent()) {
        // Both a ModuleLifecycleHooks and a JobHooks implementation were found in the same jar --
        // a real descriptor should declare at most one of the two (hooks for a long-running
        // service, jobHooks for a Job-kind module), so this is left in as a TODO rather than
        // silently picking one.
        sb.append(
            "  # jobHooks and hooks were both detected -- a module normally declares only"
                + " one, matching its workload kind. TODO: keep the one that applies and delete the"
                + " other.\n");
      }
      sb.append("  jobHooks: ").append(detected.jobHooksClass().get()).append('\n');
    }
  }
}
