/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as GjallarhornRouteImport } from './routes/gjallarhorn'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as TestsTestIdRouteImport } from './routes/tests.$testId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const GjallarhornRoute = GjallarhornRouteImport.update({
  id: '/gjallarhorn',
  path: '/gjallarhorn',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsTestIdRoute = TestsTestIdRouteImport.update({
  id: '/tests/$testId',
  path: '/tests/$testId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/gjallarhorn': typeof GjallarhornRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/tests/$testId': typeof TestsTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/gjallarhorn': typeof GjallarhornRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/tests/$testId': typeof TestsTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/gjallarhorn': typeof GjallarhornRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/tests/$testId': typeof TestsTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/compare' | '/gjallarhorn' | '/runs/$runId' | '/tests/$testId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compare' | '/gjallarhorn' | '/runs/$runId' | '/tests/$testId'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/gjallarhorn'
    | '/runs/$runId'
    | '/tests/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  GjallarhornRoute: typeof GjallarhornRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  TestsTestIdRoute: typeof TestsTestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gjallarhorn': {
      id: '/gjallarhorn'
      path: '/gjallarhorn'
      fullPath: '/gjallarhorn'
      preLoaderRoute: typeof GjallarhornRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$testId': {
      id: '/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof TestsTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  GjallarhornRoute: GjallarhornRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  TestsTestIdRoute: TestsTestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
