/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellRepositoryRouteImport } from './routes/_shell.repository'
import { Route as ShellArtifactsIndexRouteImport } from './routes/_shell.artifacts.index'
import { Route as ShellArtifactsModuleIdRouteImport } from './routes/_shell.artifacts.$moduleId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRepositoryRoute = ShellRepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => ShellRoute,
} as any)
const ShellArtifactsIndexRoute = ShellArtifactsIndexRouteImport.update({
  id: '/artifacts/',
  path: '/artifacts/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellArtifactsModuleIdRoute = ShellArtifactsModuleIdRouteImport.update({
  id: '/artifacts/$moduleId',
  path: '/artifacts/$moduleId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/repository': typeof ShellRepositoryRoute
  '/artifacts/$moduleId': typeof ShellArtifactsModuleIdRoute
  '/artifacts/': typeof ShellArtifactsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/repository': typeof ShellRepositoryRoute
  '/': typeof ShellIndexRoute
  '/artifacts/$moduleId': typeof ShellArtifactsModuleIdRoute
  '/artifacts': typeof ShellArtifactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/repository': typeof ShellRepositoryRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/artifacts/$moduleId': typeof ShellArtifactsModuleIdRoute
  '/_shell/artifacts/': typeof ShellArtifactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/repository' | '/artifacts/$moduleId' | '/artifacts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/repository' | '/' | '/artifacts/$moduleId' | '/artifacts'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/_shell/repository'
    | '/_shell/'
    | '/_shell/artifacts/$moduleId'
    | '/_shell/artifacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/repository': {
      id: '/_shell/repository'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof ShellRepositoryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/artifacts/': {
      id: '/_shell/artifacts/'
      path: '/artifacts'
      fullPath: '/artifacts/'
      preLoaderRoute: typeof ShellArtifactsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/artifacts/$moduleId': {
      id: '/_shell/artifacts/$moduleId'
      path: '/artifacts/$moduleId'
      fullPath: '/artifacts/$moduleId'
      preLoaderRoute: typeof ShellArtifactsModuleIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellRepositoryRoute: typeof ShellRepositoryRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellArtifactsModuleIdRoute: typeof ShellArtifactsModuleIdRoute
  ShellArtifactsIndexRoute: typeof ShellArtifactsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellRepositoryRoute: ShellRepositoryRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellArtifactsModuleIdRoute: ShellArtifactsModuleIdRoute,
  ShellArtifactsIndexRoute: ShellArtifactsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
