import type {
  CronJob,
  CustomResourceItem,
  DaemonSet,
  Deployment,
  Job,
  KindDefinitionSummary,
  Service,
  StatefulSet,
} from "@/types";
import { fromCustomResource } from "@/addons/applications/kinds/custom";
import { fromCronJob, fromJob } from "@/addons/applications/kinds/jobs";
import {
  fromDaemonSet,
  fromDeployment,
  fromStatefulSet,
} from "@/addons/applications/kinds/replicated";
import { compareApplications, type Application } from "@/addons/applications/model";

/** Everything one refresh read, before it is folded into applications. */
export interface ClusterWorkloads {
  deployments: readonly Deployment[];
  statefulSets: readonly StatefulSet[];
  daemonSets: readonly DaemonSet[];
  jobs: readonly Job[];
  cronJobs: readonly CronJob[];
  customResources: readonly CustomResourceItem[];
  kindDefinitions: readonly KindDefinitionSummary[];
  services: readonly Service[];
}

export const NO_WORKLOADS: ClusterWorkloads = {
  deployments: [],
  statefulSets: [],
  daemonSets: [],
  jobs: [],
  cronJobs: [],
  customResources: [],
  kindDefinitions: [],
  services: [],
};

/**
 * Every deployable resource in the cluster as one sorted application list, worst health first.
 *
 * A Job generated by a CronJob appears twice on purpose: once as its own application (it is a real
 * workload with its own logs and its own failure) and once as a row under the schedule that
 * produced it, which is where an operator looks to see whether the schedule is working.
 */
export function buildApplications(c: ClusterWorkloads): Application[] {
  const definitionsByKind = new Map(c.kindDefinitions.map((d) => [d.kindName, d]));
  const apps: Application[] = [
    ...c.deployments.map((d) => fromDeployment(d, c.services)),
    ...c.statefulSets.map((s) => fromStatefulSet(s, c.services)),
    ...c.daemonSets.map((d) => fromDaemonSet(d, c.services)),
    ...c.jobs.map((j) => fromJob(j, c.services)),
    ...c.cronJobs.map((cj) => fromCronJob(cj, c.jobs, c.services)),
    ...c.customResources.map((r) => fromCustomResource(r, definitionsByKind.get(r.kind))),
  ];
  return apps.sort(compareApplications);
}
