import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// A single autogenerated sidebar, derived straight from the docs/ folder structure and each
// page's own sidebar_position frontmatter -- no manually-curated item list to keep in sync as
// pages are added, moved, or renamed.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
