package com.gimle.holmgang.rtm;

import com.gimle.core.protocol.Json;
import com.gimle.holmgang.HolmgangException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Parses {@code rtm.json}'s {@code requirements} array (one object per requirement: id, feature,
 * category, module, status, coverage) and checks it for implemented-but-uncovered requirements.
 * Reads the structured JSON source of truth directly -- generated by {@code
 * scripts/generate_requirements_docs.py}, the same source {@code RTM.md} itself is rendered from --
 * rather than scraping the generated Markdown, so a Markdown-only formatting change can never
 * silently break this parser the way scraping the rendered tables/prose used to.
 */
public final class RtmCoverageChecker {

  /** One requirement from {@code rtm.json}'s {@code requirements} array. */
  public record RtmEntry(
      String id, String feature, String category, String status, String coverage) {

    /** {@code Removed} requirements are no longer in the codebase and are never gated on. */
    public boolean isImplemented() {
      return !status.equalsIgnoreCase("Removed");
    }

    public boolean isCovered() {
      return coverage.equalsIgnoreCase("Covered");
    }
  }

  /** {@code rtm.json}'s requirements, in file order. */
  public record RtmDocument(List<RtmEntry> entries) {}

  /** The outcome of checking a document's entries against an exclusion list. */
  public record CoverageResult(
      int totalChecked, List<RtmEntry> notCovered, List<String> unknownExcludedIds) {

    public boolean passed() {
      return notCovered.isEmpty();
    }
  }

  private static final String REQUIREMENTS_KEY = "requirements";
  private static final String ID_KEY = "id";
  private static final String FEATURE_KEY = "feature";
  private static final String CATEGORY_KEY = "category";
  private static final String STATUS_KEY = "status";
  private static final String COVERAGE_KEY = "coverage";

  private RtmCoverageChecker() {}

  /**
   * Reads and parses {@code rtmFile}. Fails loudly -- never returns a silently empty or partial
   * document -- whenever the file is missing/unreadable or its structure isn't recognizable, since
   * a coverage gate that silently sees zero requirements is worse than no gate at all.
   */
  public static RtmDocument parse(final Path rtmFile) {
    if (!Files.isRegularFile(rtmFile)) {
      throw new HolmgangException(
          "RTM coverage gate enabled but rtm.json was not found at "
              + rtmFile.toAbsolutePath()
              + " -- generate it (and RTM.md alongside it) with"
              + " scripts/generate_requirements_docs.py, override its location with"
              + " -Dgimle.holmgang.rtmCheck.file=<path>, or disable the gate with"
              + " -Dgimle.holmgang.rtmCheck.enabled=false");
    }
    final String content;
    try {
      content = Files.readString(rtmFile);
    } catch (final IOException e) {
      throw new HolmgangException("failed reading RTM file " + rtmFile.toAbsolutePath(), e);
    }
    return parseContent(content, rtmFile.toString());
  }

  /** Package-visible for direct unit testing without touching the filesystem. */
  static RtmDocument parseContent(final String content, final String sourceLabel) {
    final Object parsed;
    try {
      parsed = Json.parse(content);
    } catch (final RuntimeException e) {
      throw new HolmgangException(
          "RTM file " + sourceLabel + " is not valid JSON -- its structure is unrecognizable", e);
    }
    if (!(parsed instanceof Map)) {
      throw new HolmgangException(
          "RTM file " + sourceLabel + " does not parse to a JSON object at its top level");
    }
    final Map<String, Object> root = Json.asObject(parsed);

    final Object requirementsValue = root.get(REQUIREMENTS_KEY);
    if (!(requirementsValue instanceof List)) {
      throw new HolmgangException(
          "RTM file "
              + sourceLabel
              + " has no '"
              + REQUIREMENTS_KEY
              + "' array at its top level -- its structure is unrecognizable; either rtm.json's"
              + " own schema changed, or this isn't an rtm.json file at all");
    }

    final List<Map<String, Object>> rawEntries = Json.asObjectList(requirementsValue);
    final List<RtmEntry> entries = new ArrayList<>();
    int index = 0;
    for (final Map<String, Object> raw : rawEntries) {
      entries.add(parseEntry(raw, index, sourceLabel));
      index++;
    }

    if (entries.isEmpty()) {
      throw new HolmgangException(
          "RTM file "
              + sourceLabel
              + "'s '"
              + REQUIREMENTS_KEY
              + "' array parsed to zero entries -- expected at least one requirement");
    }
    return new RtmDocument(List.copyOf(entries));
  }

  private static RtmEntry parseEntry(
      final Map<String, Object> raw, final int index, final String sourceLabel) {
    final String id = requireString(raw, ID_KEY, index, sourceLabel);
    final String feature = requireString(raw, FEATURE_KEY, index, sourceLabel);
    final String category = requireString(raw, CATEGORY_KEY, index, sourceLabel);
    final String status = requireString(raw, STATUS_KEY, index, sourceLabel);
    final String coverage = requireString(raw, COVERAGE_KEY, index, sourceLabel);

    if (!id.matches("GIMLE-\\d+")) {
      throw new HolmgangException(
          "RTM file "
              + sourceLabel
              + " requirements["
              + index
              + "] has an unrecognizable requirement ID (expected GIMLE-<number>): '"
              + id
              + "'");
    }
    if (!coverage.equalsIgnoreCase("Covered") && !coverage.equalsIgnoreCase("Not Covered")) {
      throw new HolmgangException(
          "RTM file "
              + sourceLabel
              + " requirements["
              + index
              + "] ("
              + id
              + ") has an unrecognized coverage value (expected 'Covered' or 'Not Covered'): '"
              + coverage
              + "'");
    }
    return new RtmEntry(id, feature, category, status, coverage);
  }

  private static String requireString(
      final Map<String, Object> raw, final String key, final int index, final String sourceLabel) {
    final Object value = raw.get(key);
    if (!(value instanceof String s) || s.isBlank()) {
      throw new HolmgangException(
          "RTM file "
              + sourceLabel
              + " requirements["
              + index
              + "] is missing a non-blank string '"
              + key
              + "' field -- its structure is unrecognizable");
    }
    return s;
  }

  /**
   * Filters {@code document}'s entries down to implemented (non-{@code Removed}) requirements not
   * in {@code excludedIds}, reporting which of those excluded IDs never matched an entry (a likely
   * typo or a since-renumbered/removed requirement).
   */
  public static CoverageResult check(final RtmDocument document, final Set<String> excludedIds) {
    final Set<String> normalizedExcluded =
        excludedIds.stream().map(id -> id.toUpperCase(Locale.ROOT)).collect(Collectors.toSet());
    final Set<String> matchedExcluded = new HashSet<>();

    final List<RtmEntry> notCovered = new ArrayList<>();
    int totalChecked = 0;
    for (final RtmEntry entry : document.entries()) {
      if (!entry.isImplemented()) {
        continue;
      }
      final String normalizedId = entry.id().toUpperCase(Locale.ROOT);
      if (normalizedExcluded.contains(normalizedId)) {
        matchedExcluded.add(normalizedId);
        continue;
      }
      totalChecked++;
      if (!entry.isCovered()) {
        notCovered.add(entry);
      }
    }

    final List<String> unknownExcludedIds =
        normalizedExcluded.stream()
            .filter(id -> !matchedExcluded.contains(id))
            .sorted()
            .collect(Collectors.toList());

    return new CoverageResult(totalChecked, List.copyOf(notCovered), unknownExcludedIds);
  }
}
