/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as DesignerBlueprintIdRouteImport } from './routes/designer.$blueprintId'
import { Route as RunnerBlueprintIdRouteImport } from './routes/runner.$blueprintId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerBlueprintIdRoute = DesignerBlueprintIdRouteImport.update({
  id: '/designer/$blueprintId',
  path: '/designer/$blueprintId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnerBlueprintIdRoute = RunnerBlueprintIdRouteImport.update({
  id: '/runner/$blueprintId',
  path: '/runner/$blueprintId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clusters': typeof ClustersRoute
  '/designer/$blueprintId': typeof DesignerBlueprintIdRoute
  '/runner/$blueprintId': typeof RunnerBlueprintIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clusters': typeof ClustersRoute
  '/designer/$blueprintId': typeof DesignerBlueprintIdRoute
  '/runner/$blueprintId': typeof RunnerBlueprintIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clusters': typeof ClustersRoute
  '/designer/$blueprintId': typeof DesignerBlueprintIdRoute
  '/runner/$blueprintId': typeof RunnerBlueprintIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/clusters' | '/designer/$blueprintId' | '/runner/$blueprintId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clusters' | '/designer/$blueprintId' | '/runner/$blueprintId'
  id:
    | '__root__'
    | '/'
    | '/clusters'
    | '/designer/$blueprintId'
    | '/runner/$blueprintId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClustersRoute: typeof ClustersRoute
  DesignerBlueprintIdRoute: typeof DesignerBlueprintIdRoute
  RunnerBlueprintIdRoute: typeof RunnerBlueprintIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer/$blueprintId': {
      id: '/designer/$blueprintId'
      path: '/designer/$blueprintId'
      fullPath: '/designer/$blueprintId'
      preLoaderRoute: typeof DesignerBlueprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runner/$blueprintId': {
      id: '/runner/$blueprintId'
      path: '/runner/$blueprintId'
      fullPath: '/runner/$blueprintId'
      preLoaderRoute: typeof RunnerBlueprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClustersRoute: ClustersRoute,
  DesignerBlueprintIdRoute: DesignerBlueprintIdRoute,
  RunnerBlueprintIdRoute: RunnerBlueprintIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
